name: 'Unit Tests'
description: 'Run unit tests with pytest and upload coverage to Codecov'

inputs: {}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Remplacez par une valeur fixe si vous ne voulez pas utiliser une variable d'environnement

    - name: Install dependencies
      run: |
        cd src
        pip install -e .
        pip install pytest pytest-cov pytest-xdist pytest-mock
      shell: bash

    - name: Run Python tests
      run: |
        cd src
        python -m pytest testing/tests/unit/ \
          -v --cov=shtest_compiler \
          --cov-report=xml \
          --cov-report=html \
          --rootdir=.
      shell: bash

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: src/coverage.xml
        flags: unittests
        name: codecov-umbrella
