name: 'Security Scan'
description: 'Run Bandit and Safety for static analysis and dependency vulnerability checks'

inputs: {}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install security tools
      run: |
        pip install bandit safety
      shell: bash

    - name: Run Bandit
      run: |
        cd src
        bandit -r shtest_compiler/ -f json -o bandit-report.json || true
      shell: bash

    - name: Run Safety
      run: |
        cd src
        safety check --json --output safety-report.json || true
      shell: bash

    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          src/bandit-report.json
          src/safety-report.json
