name: Build Documentation
on:
  workflow_call:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    using: "composite"

    steps:
      - uses: actions/checkout@v4

     # install python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # install node
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # install mkdocs dependencies
      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs-macros-plugin mkdocs-minify-plugin
          npm install -g @mermaid-js/mermaid-cli

      # Generate assets diagrams
      - name: Generate architecture diagram
        run: |
          npx mmdc --no-sandbox -i docs/docs/assets/architecture.mmd -o docs/docs/assets/architecture.png || echo "Mermaid generation failed (possibly headless issue)."
      - name: Build documentation
        run: |
          cd docs
          mkdocs build

      # Deploy to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
          cname: knightbatch.github.io
