# Alias pour traduire le langage naturel vers des expressions techniques normalisées
# Format: "expression naturelle": "expression technique normalisée"
# Chaque commande normalisée peut avoir plusieurs formulations naturelles

# ===== ACTIONS =====

# Affichage de fichier
afficher le contenu du fichier: "fichier affiché"
voir le contenu du fichier: "fichier affiché"
lire le fichier: "fichier affiché"
consulter le fichier: "fichier affiché"
ouvrir le fichier: "fichier affiché"

# Copie de fichiers
copier le fichier: "fichier copié"
dupliquer le fichier: "fichier copié"
reproduire le fichier: "fichier copié"
faire une copie du fichier: "fichier copié"
le fichier est copié: "fichier copié"
le fichier a été copié: "fichier copié"
la copie du fichier a réussi: "fichier copié"
le fichier a été dupliqué: "fichier copié"

# Copie de dossiers
copier le dossier: "dossier copié"
dupliquer le dossier: "dossier copié"
reproduire le dossier: "dossier copié"
faire une copie du dossier: "dossier copié"
le dossier est copié: "dossier copié"
le dossier a été copié: "dossier copié"
la copie du dossier a réussi: "dossier copié"
le dossier a été dupliqué: "dossier copié"

# Création de dossiers
créer le dossier: "dossier créé"
nouveau dossier: "dossier créé"
faire un dossier: "dossier créé"
construire le dossier: "dossier créé"
le dossier est prêt: "dossier créé"
le dossier existe: "dossier créé"
le dossier a été créé: "dossier créé"
le répertoire est disponible: "dossier créé"
le répertoire existe: "dossier créé"
le dossier est cree: "dossier créé"
le dossier est créé: "dossier créé"

# Création de fichiers
créer le fichier: "fichier créé"
nouveau fichier: "fichier créé"
faire un fichier: "fichier créé"
construire le fichier: "fichier créé"
le fichier est créé: "fichier créé"
le fichier existe: "fichier créé"
le fichier a été créé: "fichier créé"
le fichier est cree: "fichier créé"
le fichier est créé: "fichier créé"

# Exécution de scripts
exécuter le script: "exécuter"
lancer le script: "exécuter"
démarrer le script: "exécuter"
faire tourner le script: "exécuter"
exécuter le programme: "exécuter"
lancer le programme: "exécuter"

# Configuration des logs
définir le chemin des logs: "chemin des logs"
configurer les logs: "chemin des logs"
spécifier les logs: "chemin des logs"
indiquer les logs: "chemin des logs"

# Nettoyage de répertoires
vider le répertoire: "vider le répertoire"
nettoyer le répertoire: "vider le répertoire"
supprimer le contenu: "vider le répertoire"
effacer le répertoire: "vider le répertoire"
purger le répertoire: "vider le répertoire"

# Définition de variables
définir la variable: "variable ... vaut"
assigner la variable: "variable ... vaut"
configurer la variable: "variable ... vaut"
spécifier la variable: "variable ... vaut"
variable sql_conn vaut: "variable SQL_CONN vaut"

# Modification de dates
toucher le fichier: "toucher le fichier"
modifier la date: "toucher le fichier"
changer la date: "toucher le fichier"
mettre à jour la date: "toucher le fichier"

# ===== RÉSULTATS/VALIDATIONS =====

# Codes de retour
retour 0: "retour 0"
code de retour 0: "retour 0"
succès: "retour 0"
réussi: "retour 0"
pas d'erreur: "retour 0"
Le script retourne un code 0: "retour 0"
le script retourne un code 0: "retour 0"
le script retourne un code 0.: "retour 0"
le script retourne un code 0: "retour 0"

retour 1: "retour 1"
code de retour 1: "retour 1"
erreur 1: "retour 1"
échec: "retour 1"

# Variables d'environnement
La variable d'environnement à été définie: "variable d'environnement définie"
la variable d'environnement à été définie: "variable d'environnement définie"
la variable d'environnement a été définie: "variable d'environnement définie"
la variable d'environnement est définie: "variable d'environnement définie"
la variable est définie: "variable d'environnement définie"
la variable a été définie: "variable d'environnement définie"

# Sortie standard - variantes génériques
la sortie standard contient: "stdout contient"
la sortie contient: "stdout contient"
le script affiche: "stdout contient"
le programme affiche: "stdout contient"
le script produit: "stdout contient"
le script affiche un code: "stdout contient"
le programme produit: "stdout contient"
le script affiche un code: "stdout contient"

# Sortie d'erreur - variantes génériques
la sortie d'erreur contient: "stderr contient"
l'erreur contient: "stderr contient"
le message d'erreur contient: "stderr contient"
l'erreur affiche: "stderr contient"

# Messages d'erreur
aucun message d'erreur: "aucun message d'erreur"
pas d'erreur: "aucun message d'erreur"
aucune erreur: "aucun message d'erreur"
pas de message d'erreur: "aucun message d'erreur"
aucune erreur n'apparaît: "aucun message d'erreur"

# Contenu
le contenu est affiché: "contenu affiché"
le contenu est visible: "contenu affiché"
le contenu s'affiche: "contenu affiché"
le script est affiché: "contenu affiché"
le fichier s'affiche: "contenu affiché"
le contenu est lisible: "contenu affiché"
le contenu peut être lu: "contenu affiché"

le contenu est correct: "contenu correct"
le contenu est bon: "contenu correct"
le contenu est valide: "contenu correct"
le contenu correspond: "contenu correct"

# Présence de fichiers/dossiers
le fichier est présent: "fichier présent"
le fichier existe: "fichier présent"
le fichier est là: "fichier présent"
le fichier est disponible: "fichier présent"

le dossier est présent: "dossier présent"
le dossier existe: "dossier présent"
le dossier est là: "dossier présent"
le dossier est disponible: "dossier présent"
le répertoire existe: "dossier présent"

# État des fichiers
le fichier est vide: "fichier vide"
le fichier ne contient rien: "fichier vide"
le fichier est sans contenu: "fichier vide"

le fichier existe: "fichier existe"
le fichier est présent: "fichier existe"
le fichier est là: "fichier existe"

# Déplacement
le fichier est déplacé: "fichier déplacé"
le fichier a été déplacé: "fichier déplacé"
le fichier est copié: "fichier déplacé"
le fichier a été copié: "fichier déplacé"
la copie du fichier a réussi: "fichier déplacé"

le dossier est déplacé: "dossier déplacé"
le dossier a été déplacé: "dossier déplacé"
le dossier est copié: "dossier déplacé"
le dossier a été copié: "dossier déplacé"
la copie du dossier a réussi: "dossier déplacé"

# Base de données
la base est prête: "base prête"
la base est prête pour le test: "base prête"
la base de test est prête: "base prête"
la base de données est prête: "base prête"
la base est disponible: "base prête"
la base est accessible: "base prête"

le script s'execute avec succès: "script exécuté avec succès"
le script s'exécute avec succès: "script exécuté avec succès"
le script fonctionne: "script exécuté avec succès"
le script a réussi: "script exécuté avec succès"
le script s'est bien passé: "script exécuté avec succès"
Le script s'execute avec succès: "script exécuté avec succès"

les identifiants sont configurés: "identifiants configurés"
identifiants configurés: "identifiants configurés"
les identifiants sont définis: "identifiants configurés"
les identifiants sont en place: "identifiants configurés"
la connexion est configurée: "identifiants configurés"

# Logs et dates
logs accessibles: "logs accessibles"
les logs sont accessibles: "logs accessibles"
les logs sont disponibles: "logs accessibles"
les logs sont lisibles: "logs accessibles"

date modifiée: "date modifiée"
la date est modifiée: "date modifiée"
la date a changé: "date modifiée"
la date a été mise à jour: "date modifiée"
date modifiee: "date modifiée"

# Comparaison de fichiers
Les fichiers sont identiques: "fichiers identiques"
les fichiers sont identiques: "fichiers identiques"
le fichier est identique: "fichiers identiques"
les fichiers correspondent: "fichiers identiques"
les fichiers sont égaux: "fichiers identiques"
les fichiers sont les mêmes: "fichiers identiques" 