name: Build Windows Executable
on:
  workflow_call:

jobs:
  build_exe:
    runs-on: windows-latest
    using: "composite"
    outputs:
      exe-path: ${{ steps.build.outputs.exe-path }}

    steps:
      - uses: actions/checkout@v4

      # Install python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install app dependencies
      - name: Install dependencies
        run: |
          cd src
          pip install -r requirements.txt
          pip install pyinstaller

      # Build the executable
      - name: Build EXE
        id: build
        run: |
          cd src
          pyinstaller `
            --onefile `
            --add-data "shtest_compiler/config;./shtest_compiler/config" `
            --add-data "shtest_compiler/regex_config.yml;." `
            shtest_compiler/shtest.py          
          echo "exe-path=src/dist/shtest.exe" >> $GITHUB_OUTPUT

      # Save artifacts
      - name: Upload EXE artifacts
        uses: actions/upload-artifact@v4
        with:
          name: knightbatch-exe
          path: src/dist/shtest.exe
