
site_name: KnightBatch Documentation
theme:
  logo: assets/logo.png
  name: material
  palette:
    scheme: slate
  code:
    highlighting: monokai
nav:
  - Accueil: index.md
  - Guide de démarrage:
    - Manuel Utilisateur: user_manual.md
    - Configuration: configuration.md
    - Outils CLI: cli.md
  - Rédaction des tests:
    - Prise en main: shtest_format.md 
    - Expressions détectées: regex_documentation.md
    - Tests et Validation: testing_and_validation.md
  - Guide développeur:
    - Démarrage rapide: developer_quickstart.md
    - Architecture Modulaire: modular_architecture.md
    - Créer un Plugin: plugin_tutorial.md
    - Guide de style: style-guide.md
  - Extensions:
    - Extension VS Code: vscode_extension.md
plugins:
  - search
  - macros

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  
