
site_name: Batch Testing Documentation
theme:
  name: material
nav:
  - Accueil: index.md
  - Outils CLI: cli.md
  - Configuration: configuration.md
  - Rédigez vos tests:
    - Prise en main : shtest_format.md
    - Expressions détéctées: regex_documentation.md
  - Guide de style: style-guide.md
  
  
