name: Docs Main

on:
  push:
    branches: [ main ]
    tags:
      - v*.*.*
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Build and Deploy Docs
        uses: ./.github/actions/docs  # Chemin vers le dossier contenant action.yml
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
