name: Docs Main

on:
  push:
    branches: [ main ]
    tags:
      - v*.*.*
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    uses: ./docs/deploy.yml
    if: startsWith(github.ref, 'refs/tags/v')