name: Docs Main

on:
  push:
    branches: [ main ]
    tags: [ docs-v* ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Deploy Docs
        uses: ./.github/actions/docs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
