name: Knight Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    env:
      python-version: ${{ matrix.python-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Unit Tests
        uses: ./.github/actions/unit-test

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Security Scan
        uses: ./.github/actions/security-scan

  build:
    runs-on: windows-latest
    outputs:
      exe-path: ${{ steps.build-step.outputs.exe-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Executable
        id: build-step
        uses: ./.github/actions/build-exe

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/kb-v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy EXE
        uses: ./.github/actions/deploy-exe
        with:
          exe-path: ${{ needs.build.outputs.exe-path }}
