name: Knight Main

on:
  push:
    branches: [ main ]
    tags:
      - v*.*.*
  pull_request:
    branches: [ main ]

jobs:




  test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    env:
      python-version: ${{ matrix.python-version }}
    steps:
      - uses: ./knight/unit-tests.yml




  security-scan:
    uses: ./knight/security-scan.yml
  



  # Knigth Batch 
  # Tag : vs-v*.*.*

  build:
    runs-on: windows-latest
    outputs:
      exe-path: ${{ steps.build-step.outputs.exe-path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build executable
        id: build-step
        uses: ./knight/build-exe.yml




  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/kb-v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy EXE
        uses: ./knight/deploy.yml
        with:
          exe-path: ${{ needs.build.outputs.exe-path }}





  
