name: Orchestrator

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  wait-for-success:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for workflows to complete
        run: echo "Ce job agit comme déclencheur logique. Les workflows déclenchés par tag s'exécuteront automatiquement."

  trigger-release:
    needs: wait-for-success
    runs-on: ubuntu-latest
    steps:
      - name: Trigger release manually
        run: |
          echo "Le tag a été poussé."
          echo "La release.yml s'exécutera grâce au trigger 'on: push: tags'"
