name: VS Code Extension

on:
  push:
    branches: [main]
    paths: ['vscode/**']
    tags: [ vs-v* ]
  pull_request:
    branches: [main]
    paths: ['vscode/**']

jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build VS Code Extension
        uses: ./.github/actions/vscode/build

  test-extension:
    runs-on: ubuntu-latest
    needs: build-extension
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Extension Unit Tests
        uses: ./.github/actions/vscode/unit-tests

  publish-extension:
    runs-on: ubuntu-latest
    needs: test-extension
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish VS Code Extension
        uses: ./.github/actions/vscode/deploy
        with:
          marketplace_token: ${{ secrets.MARKETPLACE_KEY }}