name: VS Code Extension

on:
  push:
    branches: [main]
    paths: ['vscode/**']
  pull_request:
    branches: [main]
    paths: ['vscode/**']

jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/vscode/build

  test-extension:
    runs-on: ubuntu-latest
    needs: build-extension
    steps:
      - uses: ./.github/actions/vscode/unit-tests

  publish-extension:
    runs-on: ubuntu-latest
    needs: test-extension
    if: startsWith(github.ref, 'refs/tags/vs-v')
    steps:
      - uses: ./.github/actions/vscode/deploy
